language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
services:
  - mysql
env:
  - "AR_VERSION=4.2.8"
  - "AR_VERSION=4.2.9"
  - "AR_VERSION=5.0.4"
  - "AR_VERSION=5.1.3"
  - "AR_VERSION=5.2.3"
sudo: false
cache: bundler
branches:
  only:
    - master
before_install:
  - mysql -e "create database activerecord_unittest;"
