name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: 'activerecord_unittest'
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
 
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7']
        gemfile: ['Gemfile', 'gemfiles/ar_6_1.gemfile']

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 3 --retry 3

    - name: Run tests
      run: bundle exec rake
